In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3],dtype=int)
b =[1,2,3]
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
print(a*2)
print(b*2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
a=np.ones((3,2))
print(a.shape)
print(len(a))

(3, 2)
3


In [20]:
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#Custom Array

temp = np.arange(1,10,2)
print(temp)
temp.sum()

[1 3 5 7 9]


25

In [16]:
#Identity Matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])